package Panels;

import java.awt.Color;
import java.awt.Font;
import java.util.Hashtable;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.text.DocumentFilter;
import numberrandomgame.AudioManager;
import numberrandomgame.Background;
import numberrandomgame.Configuration;
import numberrandomgame.Drive;

/**
 *
 * @author funer
 */
public class Settings extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Settings.class.getName());

    Background bg = new Background(); 
    public Settings() {
    configureWindow();
    Heart.setSelectedItem(String.valueOf(Configuration.heart));
    Time.setText(String.valueOf(Configuration.timeForQuestion));
    Increment.setSelectedItem(String.valueOf(Configuration.increment));
    ((javax.swing.text.PlainDocument) Time.getDocument()).setDocumentFilter(new javax.swing.text.DocumentFilter() {
        @Override
        public void insertString(DocumentFilter.FilterBypass fb, int off, String str, javax.swing.text.AttributeSet a) throws javax.swing.text.BadLocationException {
            if (str.matches("\\d+")) super.insertString(fb, off, str, a);
        }
        @Override
        public void replace(DocumentFilter.FilterBypass fb, int off, int len, String str, javax.swing.text.AttributeSet a) throws javax.swing.text.BadLocationException {
            if (str.matches("\\d+")) super.replace(fb, off, len, str, a);
        }
    });
    Heart.setBackground(new java.awt.Color(255, 220, 100));
    Heart.setForeground(new java.awt.Color(255, 220, 100));
    Heart.setRenderer(new javax.swing.DefaultListCellRenderer() {
        @Override
        public java.awt.Component getListCellRendererComponent(
            javax.swing.JList<?> list, Object value, int index,
            boolean isSelected, boolean cellHasFocus) {
            java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            c.setForeground(new java.awt.Color(255, 120, 0));
            if (isSelected) {
                c.setBackground(new java.awt.Color(100, 0, 0));
                c.setForeground(new java.awt.Color(255, 220, 100));
            } else {
                c.setBackground(new java.awt.Color(40, 0, 0));
            }
            return c;
        }
    });
    Increment.setBackground(new java.awt.Color(255, 220, 100));
    Increment.setForeground(new java.awt.Color(255, 220, 100));
    Increment.setRenderer(new javax.swing.DefaultListCellRenderer() {
        @Override
        public java.awt.Component getListCellRendererComponent(
            javax.swing.JList<?> list, Object value, int index,
            boolean isSelected, boolean cellHasFocus) {
            java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            c.setForeground(new java.awt.Color(255, 120, 0));
            if (isSelected) {
                c.setBackground(new java.awt.Color(100, 0, 0));
                c.setForeground(new java.awt.Color(255, 220, 100));
            } else {
                c.setBackground(new java.awt.Color(40, 0, 0));
            }
            return c;
        }
    });

    volume.setMinimum(0);
    volume.setMaximum(100);

    float decibelios = AudioManager.getVolumen();
    int porcentaje = (int) (Math.pow(10, decibelios / 40) * 100);
    volume.setValue(porcentaje);

    volume.setForeground(new Color(255, 140, 0));
    volume.setBackground(new Color(30, 30, 30));
    volume.setFont(new Font("Serif", Font.BOLD, 16));
    volume.setPaintTicks(true);
    volume.setMajorTickSpacing(20);
    volume.setMinorTickSpacing(5);
    volume.setPaintLabels(true);

    Hashtable<Integer, JLabel> etiquetas = new Hashtable<>();
    etiquetas.put(0, new JLabel("Bajo"));
    etiquetas.put(50, new JLabel("Medio"));
    etiquetas.put(100, new JLabel("Alto"));
    for (JLabel lbl : etiquetas.values()) {
        lbl.setFont(new Font("Serif", Font.BOLD, 30));
        lbl.setForeground(new Color(0, 0, 0));
    }
    volume.setLabelTable(etiquetas);

    volume.addChangeListener(e -> {
        if (!volume.getValueIsAdjusting()) {
            int nuevoPorcentaje = volume.getValue();
            float nuevoDecibelios = (float) (Math.log10(nuevoPorcentaje / 100.0) * 40);
            AudioManager.setVolumen(nuevoDecibelios);
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameOver = new javax.swing.JPanel();
        NumbersText = new javax.swing.JLabel();
        Increment = new javax.swing.JComboBox<>();
        IncrementText = new javax.swing.JLabel();
        VolumeText = new javax.swing.JLabel();
        volume = new javax.swing.JSlider();
        SegundosText = new javax.swing.JLabel();
        Settigs = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        TimeText = new javax.swing.JLabel();
        HeartText = new javax.swing.JLabel();
        Heart = new javax.swing.JComboBox<>();
        BackButton = new javax.swing.JButton();
        Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GameOver.setOpaque(false);
        GameOver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumbersText.setFont(new java.awt.Font("Impact", 0, 55)); // NOI18N
        NumbersText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumbersText.setText("de numeros");
        GameOver.add(NumbersText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        Increment.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Increment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        Increment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 5, true));
        GameOver.add(Increment, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 110, 80));

        IncrementText.setFont(new java.awt.Font("Impact", 0, 55)); // NOI18N
        IncrementText.setText("Incremento");
        GameOver.add(IncrementText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        VolumeText.setFont(new java.awt.Font("Impact", 0, 60)); // NOI18N
        VolumeText.setText("Volumen");
        GameOver.add(VolumeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));
        GameOver.add(volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 1030, 80));

        SegundosText.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        SegundosText.setText("S");
        GameOver.add(SegundosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 340, -1, -1));

        Settigs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SettingsText.png"))); // NOI18N
        GameOver.add(Settigs, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -10, -1, -1));

        Time.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Time.setText("10");
        Time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 5));
        Time.addActionListener(this::TimeActionPerformed);
        GameOver.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 100, 80));

        TimeText.setFont(new java.awt.Font("Impact", 0, 60)); // NOI18N
        TimeText.setText("Tiempo");
        GameOver.add(TimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, -1, -1));

        HeartText.setFont(new java.awt.Font("Impact", 0, 60)); // NOI18N
        HeartText.setText("Vidas");
        GameOver.add(HeartText, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        Heart.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Heart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        Heart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 5, true));
        GameOver.add(Heart, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 110, 80));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackButton.png"))); // NOI18N
        BackButton.setBorder(null);
        BackButton.setContentAreaFilled(false);
        BackButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackButtonGray.png"))); // NOI18N
        BackButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackButtonGray.png"))); // NOI18N
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackButtonMouseReleased(evt);
            }
        });
        BackButton.addActionListener(this::BackButtonActionPerformed);
        GameOver.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, -1, -1));

        Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PrincipalFrame.png"))); // NOI18N
        GameOver.add(Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GameOver, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       // Guardar primero
    Configuration.heart = Integer.parseInt((String) Heart.getSelectedItem());

    if (Time.getText().trim().isEmpty()) {
        Configuration.timeForQuestion = 10;
    } else {
        Configuration.timeForQuestion = Integer.parseInt(Time.getText().trim());
    }

    Configuration.timeForQuestion = Integer.parseInt(Time.getText());
    Configuration.increment = Integer.parseInt((String) Increment.getSelectedItem());

    if (Drive.level == 0) {
        try {
            new Home().setVisible(true);
        } catch (Exception ex) {
            System.getLogger(Settings.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    } else { 
        new Results().setVisible(true);
    }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BackButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseReleased
        BackButton.setLocation(BackButton.getX(), BackButton.getY() - 2);
    }//GEN-LAST:event_BackButtonMouseReleased

    private void BackButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMousePressed
        BackButton.setLocation(BackButton.getX(), BackButton.getY() + 2);
    }//GEN-LAST:event_BackButtonMousePressed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonMouseClicked

    private void TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeActionPerformed
        
    }//GEN-LAST:event_TimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Settings().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Frame;
    private javax.swing.JPanel GameOver;
    private javax.swing.JComboBox<String> Heart;
    private javax.swing.JLabel HeartText;
    private javax.swing.JComboBox<String> Increment;
    private javax.swing.JLabel IncrementText;
    private javax.swing.JLabel NumbersText;
    private javax.swing.JLabel SegundosText;
    private javax.swing.JLabel Settigs;
    private javax.swing.JTextField Time;
    private javax.swing.JLabel TimeText;
    private javax.swing.JLabel VolumeText;
    private javax.swing.JSlider volume;
    // End of variables declaration//GEN-END:variables
private void configureWindow() {
    setUndecorated(true);
    initComponents();
    setExtendedState(JFrame.MAXIMIZED_BOTH);
    bg.setLayout(new java.awt.BorderLayout());
    bg.add(GameOver);
    setContentPane(bg);
}
}
